# Generated by Django 4.2 on 2023-05-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkfade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=2000, null=True)),
                ('link', models.CharField(max_length=3000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='link',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='name',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='facebook',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='instagram',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='twitter',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='youtube',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
