# Generated by Django 4.2 on 2023-05-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkfade', '0002_address_remove_socialmedia_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
