# Generated by Django 4.2 on 2023-05-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkfade', '0004_mydata_delete_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mydata',
            old_name='link',
            new_name='address_link',
        ),
        migrations.AddField(
            model_name='mydata',
            name='email_link',
            field=models.EmailField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mydata',
            name='phone_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
