# Generated by Django 4.2 on 2023-05-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondez_vous', '0002_remove_category_coupe_coupe_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupe',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coupe',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coupe',
            name='description_fr',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coupe',
            name='description_it',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='coupe',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coupe',
            name='name_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='coupe',
            name='name_it',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coupe',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
