# Generated by Django 4.2 on 2023-05-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondez_vous', '0004_alter_coupe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupe',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
