# Generated by Django 4.2 on 2023-05-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondez_vous', '0005_alter_coupe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupe',
            name='price',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
