# Generated by Django 4.2 on 2023-05-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondez_vous', '0006_alter_coupe_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max length 200 lettre', max_length=200)),
                ('email', models.EmailField(help_text='max length 300 lettre', max_length=300)),
                ('message', models.TextField(help_text='enter less than 2500 lettre', max_length=2500)),
            ],
        ),
    ]
