# Generated by Django 4.2 on 2023-05-29 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rondez_vous', '0007_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max length 200 lettre', max_length=200)),
                ('email', models.EmailField(help_text='max length 300 lettre', max_length=300)),
                ('phone', models.CharField(max_length=50)),
                ('date_start', models.DateTimeField(auto_now=True, null=True)),
                ('appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('complated', models.BooleanField(default=False)),
                ('coupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CoupeAppointmet', to='rondez_vous.coupe')),
            ],
        ),
    ]
