# Generated by Django 4.2 on 2023-05-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondez_vous', '0008_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_start',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_datetime',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='coupe',
        ),
        migrations.AddField(
            model_name='appointment',
            name='data',
            field=models.TextField(max_length=15000, null=True),
        ),
    ]
