# Generated by Django 4.2 on 2023-06-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rondez_vous', '0009_rename_date_start_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment',
            field=models.CharField(default='', help_text='max length 400 lettre', max_length=400),
            preserve_default=False,
        ),
    ]
